feat(AuthTokenVerifier):  adding verification of P-256 signed token
energywebfoundation/passport-did-auth pull request #187
Opened 2021-10-28 22:48 UTC by knzeng-e

### Summary

|             |   |
|-------------|---|
| Description |  This PR adds verification of `ECDSA P-256 SHA-256` signed tokens  |
| Jira issue  |  https://energyweb.atlassian.net/browse/PDA-22  |

#### Type of request

- [x] feature (non-breaking change)

2021-11-01 08:37 UTC, JGiter requested changes

2021-11-01 08:37 UTC, JGiter commented on lib/AuthTokenVerifier.ts
> +          return (decodedClaim !== undefined || this.p256verify(token, publickey));
PR https://github.com/energywebfoundation/ew-did-registry/pull/349 includes verification of ES256. To enable it, `jwt.verify` should be passed array of methods [`ES256`, `ES256K`]

2021-11-02 06:42 UTC, jrhender commented
@knzeng-e Thanks for your work on this PR. I think it was good to have in case Stedin wanted to test sooner. I think now that we have verification built into ew-did-registry, we should use that directly and so I think this PR can be closed.

2021-11-03 08:14 UTC, knzeng-e commented
> @knzeng-e Thanks for your work on this PR. I think it was good to have in case Stedin wanted to test sooner. I think now that we have verification built into ew-did-registry, we should use that directly and so I think this PR can be closed.

Yes @jrhender I agree. Thank you !

2021-11-03 08:14 UTC, closed without merging